### PR TITLE
MSVC compatibility

### LINKED ISSUE #6: MSVC compatibility
I noticed these UGens do not compile under Windows MSVC 2019. Would you have any interest in accepting a PR to add support for that compiler? I played with it a bit last night and got a few of the components in this repo compiling without too many changes.

### PR DESCRIPTION
**Pull request by brianlheim**
This adds the ability to compile the repo on Windows with MSVC 2019. Fixes #6 .

MiBraids is the only one I couldn't port, because libsamplerate is exceptionally hard to compile on Windows it seems.

Some of this required changes in files that seem to be copied from other projects (vcvrack, eurorack/smtlib), I hope it's alright to modify them here directly.

I tested them just now in SuperCollider 3.11.2 and they sound really good (I would expect no less!). The only one I didn't test was MiWarps since it's missing a documentation file / code samples.

I've also added a `win-build.sh` script and instructions for using it in the readme. I'm not very good with batch or powershell files and git-bash is relatively easy to install, so I thought this would be better than nothing.

### CODE REVIEW

**Comment by brianlheim** [comment]
thanks to a hint from @dvzrv I discovered libsamplerate is much easier to build on Windows in the latest version. so, i've updated the submodule and added it to the win-build.sh script. i tested the result and it sounds good to me. thanks for porting these!

**Comment by guillaume-leo** [comment]
hey, everyone, I'm trying to build on windows, I've installed CMake, Visual studio 2017 and windows SDK.
When I run the script with the command in gitBash, it return this :
$ ./win-build.sh C:\Users\guill\Documents\supercollider
Building libsamplerate
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:

  C:\Program Files (x86)\Microsoft Visual
  Studio\2019\Professional\VC\Tools\MSVC\14.20.27508\bin\Hostx64\x64.
Call Stack (most recent call first):
  CMakeLists.txt:20 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/guill/Documents/mi-UGens/MiBraids/libsamplerate/build/CMakeFiles/CMakeOutput.log".

Do you have an idea of what I'm doing wrong? Or how to solve this problem? Thank you very much 

Guillaume

**Comment by brianlheim** [comment]
probably your SC_PATH setting is wrong -- you shouldn't be writing paths like that with backslashes in git bash terminal i think.

**Comment by guillaume-leo** [comment]
You were right, the built is done, now I've a new error message but from supercollider when I boot the server (for every mi-UGens):

*** ERROR: LoadLibrary 'C:\Users\guill\AppData\Local\SuperCollider\Extensions\MiRings.scx' err '%1 is not a valid Win32 application.

Sounds like 32/64bit broblem no?

**Comment by brianlheim** [comment]
could be, I do not work much on windows. are you running 32bit SC for some reason?

**Comment by guillaume-leo** [comment]
I don't know why these ugens were built in 32bit, anyway in supercollider 32bit is working...

**Comment by brianlheim** [comment]
sorry, I am not sure I understand what you mean, but in any case it is very easy to tell cmake whether to build for 32 bit or 64 bit x86 architecture so will just add a switch for that in a new PR. thanks for your patience!

**Comment by guillaume-leo** [comment]
Well, on my computer cmake built the UGENS in 32bit and I don't know why but to solve that I can try. The thing is I really don't know how to "force" CMAKE to build in 64bit... I need to write something inside the script I suppose?

thanks for you help :)

**Comment by brianlheim** [comment]
like i said, i'll make a PR to fix it, no further action necessary on your end :)

**Comment by brianlheim** [comment]
if you are curious the solution is to pass the correct architecture option to cmake during the configuration step: https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2015%202017.html#platform-selection

**Comment by guillaume-leo** [comment]
Thank you brianlheim for this hint, should I add this line somewhere in the windows script? or in each CMakeLists files?

Thank you very much for your help

**Pull request merged**
