### PR TITLE
Plugin packaging

### PR DESCRIPTION
**Pull request by ndr-brt**
As discussed in #8 
This PR give the possibility to build and store artifacts on github releases (as this example on my fork: https://github.com/ndr-brt/mi-UGens/releases/tag/v0.0.23)
The release process will start pushing a tag in the format `vx.y.z`.

Every zip file then can be unzipped into the extensions folder of supercollider.

### CODE REVIEW

**Comment by ndr-brt** [comment]
After then, some small refactorings can be do on every build script, because they use different folders to store the binaries

**Comment by ndr-brt** [comment]
Seems like windows build failed for some reason...

**Comment by v7b1** [comment]
yes, I'm on it

**Comment by v7b1** [comment]
@ndr-brt thanks for helping out! looks like it's running fine now. will do some refactoring and update of the readme later

**Pull request merged**
